// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kriez.HomeDashboard.Data;

namespace kriez.HomeDashboard.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200119204103_Calendar")]
    partial class Calendar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kriez.HomeDashboard.Data.Models.CalendarItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CalendarItems");
                });

            modelBuilder.Entity("kriez.HomeDashboard.Data.Models.HueLight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReachable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Group");

                    b.ToTable("HueLights");
                });

            modelBuilder.Entity("kriez.HomeDashboard.Data.Models.HueScene", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HueScenes");
                });

            modelBuilder.Entity("kriez.HomeDashboard.Data.Models.UpdateTable", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("UpdateTables");
                });

            modelBuilder.Entity("kriez.HomeDashboard.Data.Models.HueLight", b =>
                {
                    b.HasOne("kriez.HomeDashboard.Data.Models.HueScene", null)
                        .WithMany("Lights")
                        .HasForeignKey("Group")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
